name: Build and Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up uv
        uses: astral-sh/setup-uv@v4


      - name: Set version
        run: |
          RAW_TAG = "${{ github.ref_name }}"
          VERSION = "${RAW_TAG//v}"
          sed -i 's/^version = .*/version = "$VERSION"/' pyproject.toml
          echo "version set to $VERSION in pyproject.toml"
          cat pyproject.toml
      - name: Build
        run: |
          rm -rf dist
          uv build --sdist --wheel --out-dir dist
          ls dist/




      #- name: publish
      #  env:
      #    UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      #  run: |
      #    uv publish
